const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.shadowcaster,
		C3.Behaviors.bound,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Behaviors.LOS,
		C3.Behaviors.MoveTo,
		C3.Plugins.Clipboard,
		C3.Behaviors.Follow,
		C3.Behaviors.Anchor,
		C3.Plugins.Text,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Behaviors.Follow.Cnds.IsFollowingObject,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.TiledBg.Cnds.IsVisible,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.ResetEventVar
	];
};
self.C3_JsPropNameTable = [
	{Platform: 0},
	{ScrollTo: 0},
	{ShadowCaster: 0},
	{BoundToLayout: 0},
	{Ohio_John: 0},
	{Solid: 0},
	{Sidewalk: 0},
	{Keyboard: 0},
	{Stone: 0},
	{Dirt: 0},
	{Pitch_Black_Cave_Background: 0},
	{Ancient_Aztec_Engraving: 0},
	{Sky: 0},
	{Cloud: 0},
	{LineOfSight: 0},
	{MoveTo: 0},
	{Easter_Egg_Snake: 0},
	{Clipboard: 0},
	{Maple_Tree: 0},
	{Pine_Tree: 0},
	{Bush: 0},
	{Sun: 0},
	{Aztec_Face: 0},
	{Follow: 0},
	{Black_Cat: 0},
	{White_Kitty: 0},
	{Aztec_Vase: 0},
	{Diggable_Dirt: 0},
	{Jaguar_48: 0},
	{Aztec_Coins: 0},
	{Aztec_Macuahuitl: 0},
	{Dirt_Gone: 0},
	{Speech_Bubble_1: 0},
	{Speech_Bubble_2: 0},
	{Speech_Bubble_3: 0},
	{Anchor: 0},
	{HUDVASE: 0},
	{HUDCOINS: 0},
	{HUDMAC: 0},
	{Text: 0},
	{Speech_Bubble_4: 0},
	{foundcoins: 0},
	{foundmac: 0},
	{foundvase: 0},
	{HOWRICHRU: 0}
];

self.InstanceType = {
	Ohio_John: class extends self.ISpriteInstance {},
	Sidewalk: class extends self.ITiledBackgroundInstance {},
	Keyboard: class extends self.IInstance {},
	Stone: class extends self.ITiledBackgroundInstance {},
	Dirt: class extends self.ITiledBackgroundInstance {},
	Pitch_Black_Cave_Background: class extends self.ITiledBackgroundInstance {},
	Ancient_Aztec_Engraving: class extends self.ITiledBackgroundInstance {},
	Sky: class extends self.ITiledBackgroundInstance {},
	Cloud: class extends self.ITiledBackgroundInstance {},
	Easter_Egg_Snake: class extends self.ISpriteInstance {},
	Clipboard: class extends self.IInstance {},
	Maple_Tree: class extends self.ITiledBackgroundInstance {},
	Pine_Tree: class extends self.ITiledBackgroundInstance {},
	Bush: class extends self.ITiledBackgroundInstance {},
	Sun: class extends self.ITiledBackgroundInstance {},
	Aztec_Face: class extends self.ITiledBackgroundInstance {},
	Black_Cat: class extends self.ISpriteInstance {},
	White_Kitty: class extends self.ISpriteInstance {},
	Aztec_Vase: class extends self.ISpriteInstance {},
	Diggable_Dirt: class extends self.ISpriteInstance {},
	Jaguar_48: class extends self.ISpriteInstance {},
	Aztec_Coins: class extends self.ITiledBackgroundInstance {},
	Aztec_Macuahuitl: class extends self.ITiledBackgroundInstance {},
	Dirt_Gone: class extends self.ITiledBackgroundInstance {},
	Speech_Bubble_1: class extends self.ITiledBackgroundInstance {},
	Speech_Bubble_2: class extends self.ITiledBackgroundInstance {},
	Speech_Bubble_3: class extends self.ITiledBackgroundInstance {},
	HUDVASE: class extends self.ISpriteInstance {},
	HUDCOINS: class extends self.ITiledBackgroundInstance {},
	HUDMAC: class extends self.ITiledBackgroundInstance {},
	Text: class extends self.ITextInstance {},
	Speech_Bubble_4: class extends self.ITiledBackgroundInstance {}
}